### ISSUE TITLE
fatal error: opencv2/videoio/videoio_c.h: No such file or directory

### ISSUE THREAD

**Issue by LolikaPadmanbhan** [dannyblueliu/YOLO-version-2-Face-detection#16]
Hi,
I have  cloned the code from the git and now trying to run an see this on jetson TX1.
it has opencv 2.4.1, and ubuntu 16.04
below is how i have made changes in make file. but when i do make i get error saying 
**fatal error: opencv2/videoio/videoio_c.h: No such file or directory
compilation terminated.
Makefile:66: recipe for target 'obj/convolutional_layer.o' failed
make: *** [obj/convolutional_layer.o] Error 1
 so some one kindly help me with it**
GPU=1
CUDNN=0
OPENCV=1
DEBUG=0

ARCH= -gencode arch=compute_53,code=[sm_53,sm_53] \
      -gencode arch=compute_53,code=sm_53 \
      -gencode arch=compute_53,code=sm_53 \
      -gencode arch=compute_53,code=[sm_53,compute_53] \
      -gencode arch=compute_53,code=[sm_53,compute_53]

# This is what I use, uncomment if you know your arch and want to specify
# ARCH=  -gencode arch=compute_52,code=compute_52

VPATH=./src/
EXEC=darknet
OBJDIR=./obj/
Thanks!

**Comment by dannyblueliu** [comment]
I think you have to switch to OpenCV 3.1.

**Comment by LolikaPadmanbhan** [comment]
Hey 
Thanks for the response. i was able to run it on my laptop with opencv3.4. however it still difficult for me to run on jetson TX1. 
And in laptop the frame rate is very less. how to increase the fps. ? and also that it detects only with min distance right ?

**Comment by dannyblueliu** [comment]
Do you have a GPU on you laptop? Yes the working range is less than 5 meters. It all depends on your camera.

**Comment by dannyblueliu** [comment]
If you have a GPU. Try to install CUDNN. It increase the framerate.

**Comment by LolikaPadmanbhan** [comment]
Thanks Man..
