### ISSUE TITLE
Combining data with yolo.weights

### ISSUE THREAD

**Issue by abagshaw** [dannyblueliu/YOLO-version-2-Face-detection#3]
Probably a stupid question: I am trying to get a model that can work on the COCO dataset _and_ detect faces. (Basically I'm just wanting to add "face" as another detected label to the `yolo.weights` file provided at https://pjreddie.com/darknet/yolo/)

I'm assuming that the only way to do this is train an entirely different weights file from scratch with all the types of objects I want it to detect (what is currently detected in `yolo.weights` plus faces)..and unfortunately I don't have a GPU in my system so that isn't going to work well.

Is there any way to combine weights files or somehow add face detection to what already exists in `yolo.weights` without running two seperate instances of yolo? Thanks!

**Comment by dannyblueliu** [comment]
You have to train from the very beginning.
