### ISSUE TITLE
Python Script

### ISSUE THREAD

**Issue by herleeyandi** [dannyblueliu/YOLO-version-2-Face-detection#5]
Is there any python script to run the demo?

**Comment by dannyblueliu** [comment]
I do not think so.

**Comment by herleeyandi** [comment]
Thank you for works man. Did you try on video?

**Comment by dannyblueliu** [comment]
No. On camera...

**Comment by herleeyandi** [comment]
So basically the darknet can use webcam as input?, or you build a script to capture from webcam?

**Comment by dannyblueliu** [comment]
It can use webcam as input indeed.

**Comment by herleeyandi** [comment]
I see. Thank you for your works.
